[build]
  base = "portfolio-repo-main"
  command = "npm run build"
  publish = "portfolio-repo-main/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
